### ISSUE TITLE
Model selection for SNP analysis

### ISSUE THREAD

**Issue by miryad** [parseq/digital-phenotyping#10]
1) Разобраться с использованием инструментов Snipper и H-IrisPlex(-S): данные ввода / вывода, ход обработки, дополнительные функции
2) Найти статьи по этим инструментам, выяснить, какие модели используются
3) Охарактеризовать, какие еще статистические модели могут применяться для предсказания фенотипических черт по нуклеотидным заменам

**Comment by npilshchikova** [comment]
Краткие обзоры литературы по предсказанию пигментации на основе ДНК (сделаны в 2015 году):

*[eye colour](https://github.com/parseq/digital-phenotyping/files/340834/HID-2162808-290616-1204-30.pdf)
*[hair colour](https://github.com/parseq/digital-phenotyping/files/340833/HID-2162810-290616-1205-32.pdf)
*[skin pigmentation](https://github.com/parseq/digital-phenotyping/files/340835/HID-2162812-290616-1210-34.pdf)

**Comment by miryad** [comment]
я просмотрела модели в HIrisPlex и Snipper, всего получилось 8 (5+3) -- это именно модели предсказания. Не очень подробно, но могу рассказать про все
