### ISSUE TITLE
Questionnaire for individual phenotypes

### ISSUE THREAD

**Issue by npilshchikova** [parseq/digital-phenotyping#7]
Необходимо составить анкету для получения информации следующих о фенотипических признаках респондентов (self-reported):

* пигментация (цвет глаз, волос, кожи)
* группа крови
* резус-фактор

Кроме того, полезно добавить в анкету вопросы об этногеографическом происхождении (может влиять на предсказание фенотипических признаков) и о биологических родителях респондента.

**Comment by miryad** [comment]
http://goo.gl/forms/0eDJYY2LcNWCRbSI3

ссылка на анкету

**Comment by miryad** [comment]
теперь есть txt версия

**Comment by npilshchikova** [comment]
Спасибо! Тогда rtf (если ты не планируешь его поддерживать в up to date состоянии) лучше удалить.

**Comment by agbragin** [comment]
Коллеги, а почему ветка под этот тикет называется `phenotype-report`, что не соответствует ни номеру issue, ни его названию (если это вообще та ветка)?

**Comment by npilshchikova** [comment]
Ссылки на анкету отправлены респондентам.
